version: 2.1

jobs:
  build ipa:
    macos:
      xcode: "16.4.0"

    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: build
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
      - checkout

      - run:
          name: Setup environment
          command: |
            mkdir -p "$FL_OUTPUT_DIR"
            xcodebuild -version
            git config --global user.email "ci@example.com"
            git config --global user.name "CI Bot"
            git config --list | grep user.

      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-

      - run:
          name: Install Ruby 3.3.6 via rbenv
          command: |
            brew install rbenv ruby-build
            eval "$(rbenv init -)"
            rbenv install 3.3.6 --skip-existing
            rbenv global 3.3.6
            ruby -v

      - run:
          name: Install Bundler & Gems
          command: |
            gem install bundler
            bundle install --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build IPA only
          command: bundle exec fastlane release

      - store_artifacts:
          path: build

workflows:
  version: 2
  ios ipa:
    jobs:
      - build ipa:
          filters:
            branches:
              only:
                - main
